# Appendices

## Appendix A: Acronyms

**BG**	Blood Glucose  
**BGI**	Blood Glucose Impact  
**CI**	Carb Impact  
**COB**	Carbs On Board  
**CR**	Carb Ratio  
**ICR**	Insulin to Carb Ratio  
**IOB**	Insulin On Board  
**ISF**	Insulin Sensitivity Factor  
**ISR**	Insulin Sensitivity Ratio  
**RIF** Recommended Insulin Fraction  
**SMB**	Super Micro Bolus  
**SR**	Sensitivity Ratio  
**UAM**	Unannounced Meals  
**ZT**	Zero-Temp  


## Appendix B: Settings

### FREEAPS X V(version)
* Closed Loop

### DEVICES
* Pump
	* Omnipod
		* Pod Settings
			* Expires
			* Pod Active Clock
			* Bolus Delivery
			* Basal Delivery
			* Alarms
			* Reservoir
			* Insulin Delivered
			* CONFIGURATION
				* Suspend Delivery
				* Disable Confirmation Beeps
				* Disable Automatic Bolus
				* Expiration Reminder
				* Change Time Zone
				* Insulin Type
				* Replace Pod
			* DEVICES
				* RileyLink/OrangeLink/EmaLink
			* DIAGNOSTICS
				* Read Pod Status
				* Play Test Beeps
				* Read Pulse Log
				* Test Command
			* POD DETAILS
				* Assigned Addresses
				* Lot
				* PI Version
				* PM Version

### SERVICES
* Nightscout
	* Nightscout Config
		* Nightscout URL
		* Nightscout Secret Key
		* Connect
		* Delete
		* Allow uploads
		* LOCAL GLUCOSE SOURCE
			* Use local glucose server
			* Port
			* Backfill glucose
* CGM
	* Type
	* TRANSMITTER ID
	* CALENDAR
		* Create events in calendar
* OTHER
	* Upload glucose to Nightscout

### Apple Health
* Connect to Apple Health

### Notifications
* GLUCOSE
	* Show glucose on the app badge
	* Always Notify Glucose
	* Also play alert sound
	* Also add source info
	* Low
	* High
* OTHER
	* Carbs Required Threshold

### CONFIGURATION
Preferences are in ***Appendix C: Preferences***

### Pump Settings
* DELIVERY LIMITS
	* Max Basal
	* Max Bolus
* DURATION OF INSULIN ACTION
	* DIA
	* Save on Pump
### Basal Profile
* SCHEDULE
	* Rate(s)
	* Add
* Save on Pump

### Insulin Sensitivities
* AUTOTUNE
	* Calculated Sensitivity
* AUTOSENS
	* Sensitivity Ratio
	* Calculated Sensitivity
* SCHEDULE
	* Rate(s)
	* Add
* Save

### Carb Ratios
* AUTOTUNE
	* Calculated Ratio
* SCHEDULE
	* Ratio(s)
	* Add
* Save

### Target Ranges
* SCHEDULE
	* Range(s)
	* Add
* Save

### Autotune
* Use Autotune
* Last Run
* Run now
* Carb Ratio
* Sensitivity
* BASAL PROFILE
	* Rate(s)
* Delete Autotune data

### DEVELOPER
* Debug options

### Animated Background
### Share logs


## Appendix C: Preferences

### FREEAPS X
* Glucose Units
* Remote control
* Recommended Insulin Fraction
* Skip Bolus screen after carbs

### OPENAPS MAIN SETTINGS
* Insulin curve
* Max IOB
* Max COB
* Max Daily Safety Multiplier
* Current Basal Safety Multiplier
* Autosens Max
* Autosens Min

### DYNAMIC SETTINGS
* Enable Dynamic ISF
* Enable Dynamic CR
* Adjustment Factor
* Use Logarithmic Formula
* Weighted Average of TDD. Weight of past 24 hours:
* Adjust Basal

### OPEN APS SMB SETTINGS
* Enable SMB Always
* Max Delta-BG Threshold SMB
* Enable SMB with COB
* Enable SMB With Temptarget
* Enable SMB After Carbs
* Allow SMB With High Temptarget
* Enable UAM
* Max SMB Basal Minutes
* SMB DeliveryRatio
* SMB Interval
* Bolus Increment

### OPENAPS TARGETS SETTINGS
* High Temptarget Raises Sensitivity
* Low Temptarget Lowers Sensitivity
* Sensitivity Raises Target
* Sensitivity Lowers Target
* Advanced Target Adjustments
* Exercise Mode
* Half Basal Exercise Target
* Wide BG Target Range

### OPENAPS OTHER SETTINGS
* Rewind Resets Autosens
* Use Custom Peak Time
* Insulin Peak Time
* Skip Neutral Temps
* Unsuspecting If No Temp
* Suspend Zeros IOB
* Bolus Snooze DIA Divisor
* Min 5m Carbimpact
* Autotune ISF Autotune Faction
* Remaining Carbs Faction
* Noisy CGM Target Multiplier

### USE AUTO ISF
* Enable AutoISF

### AUTOISF SETTINGS
FORGET ABOUT THESE IF AUTO ISF IS TOGGLED OFF

* Enable Floating Carbs
* Enable AutoISF with COB
* Enable BG acceleration in AutoISF 2.2
* AutoISF HourlyMaxChange
* AutoISF Max
* SMB Max RangeExtension
* SMB DeliveryRatio BG Range
* SMB DeliveryRatio BG Minimum
* SMB DeliveryRatio BG Maximum
* ISF weight while BG accelerates
* ISF weight while BG decelerates
* AutoISF Min
* ISF Weight for higher BGs
* ISF weight for lower BGs
* ISF weight for higher BG deltas
* Enable always postprandial ISF adaption
* ISF weight for postprandial BG rise
* Duration ISF postprandial adaption

