# BC Diabetes Looping Agreement
Informed Consent and Waiver for Adults (18 years and older)  
Dr. Tom Elliott, Medical Director of Dr. T.G. Elliott Inc. (**BCDiabetes**)  
https://w.smrtwvr.com/w/5fc54955413f2/web/

## Background

Diabetes causes the level of glucose (sugar) in your blood to become too high. It happens when your body cannot produce enough of a hormone called insulin, which controls blood glucose. The advent of *Artificial Pancreas Systems* (APS, also known as Automated Insulin Delivery systems or AID) has provided the potential to significantly improve diabetes management and quality of life among people living with *Type 1* and *Type 2* diabetes in real-life conditions.

*Artificial Pancreas Systems* (APS or APSs) are the combination of a smart insulin pump, integrated CGM and interoperable automated glycemic controller (typically a smartphone with the necessary apps). APSs are sometimes called closed-loop systems, because they work near-automatically, with minimal user input. When properly managed, APSs offer eligible patients with *Type 1* diabetes or *Type 2* diabetes superior glycemic control and safety over conventional treatments. APSs have been in use since 2008 for people living with *Type 1* or *Type 2* diabetes, but until 2018 these were all experimental. Treatments and devices are called experimental when they have not been fully approved by a national regulatory agency. In Canada this agency is called Health Canada; in the United States the agency is called the FDA; in Europe the agency is called the EMA. Currently a number of APSs are available but some are still experimental including all Do-it-Yourself (DIY) APSs, those that are not solely commercially manufactured, produced, and implemented. If you are reading this document you may be considering using a DIY APS. All DIY APSs are still experimental.

When a drug or device is approved for medical use by the Food and Drug Administration (FDA) of the United States or Health Canada, the manufacturer produces a label to explain its use. Once a device/medication is approved by the FDA or Health Canada, physicians may prescribe it according to the label or use it off-label for other purposes. They may only prescribe it off-label if they are well-informed about the product, base its use on firm scientific methods and sound medical evidence, and maintain records of its use and effects. Although both the **Omnipod* Eros* and *Dash* pumps and *Dexcom G6* CGM are individually approved by Health Canada, the FDA and the EMA, their use together in a DIY APS is off-label and the entire DIY APS is considered experimental. This is because the software driving DIY APSs is not approved by any agency.

## What We Believe

**BCDiabetes** believes that it should continue to offer people who use APSs, either DIY or commercial systems, the care and support they deserve and to which they are entitled. BCDiabetes cannot recommend the use of DIY APSs because no DIY APS is currently approved by any regulatory agency, including Health Canada. **BCDiabetes** must ensure that people with diabetes who are using, or planning to use a DIY APS, do so at their own risk. This is because DIY APSs, no matter how sophisticated they appear, are still considered experimental. These DIY closed-loop systems have typically been built by people with diabetes or parents of children with diabetes, for their personal use (or that of their children). Safety is a major consideration for people building and using these systems.

People intending to use DIY APSs should be aware that they do this at their own risk, they may not receive support from their healthcare professional with any technical issues and that liability is unclear if there is a malfunction, error or problem. People intending to use DIY APSs should be competent and confident in optimizing their diabetes management using an insulin pump and CGM or flash glucose monitoring device. People intending to use a DIY APS can access support from the online DIY technology community for advice and troubleshooting. However, they must be aware that this advice is not regulated and they do so at their own risk.

## Approved AP Systems

There are currently two commercial APSs approved by Health Canada (and three or more approved by the FDA and the EMA) some of which may not be fully covered by BC Pharmacare or private or public drug insurance providers. [This link](https://bit.ly/39eyA6V7b) describes all insulin pump systems, including APSs available in Canada. 

* **Medtronic 670G and 770G tubed system** that currently offers temp basal adjustment. The pump and tubing are covered by BC Pharmacare but the *Medtronic Guardian 3 CGM* is not covered by BC Pharmacare.
 
 * **Tandem T-slim Control IQ tubed system** that offers temp basal and microbolus adjustment: the *Dexcom G6* CGM is covered by BC Pharmacare but the *Tandem T-slim pump* itself is not covered by BC Pharmacare.

Health Canada is currently considering two other commercial APS submissions:

 * The **Omnipod 5** system tubeless pump system (the pump of which, the **Omnipod Dash*, is covered by BC Pharmacare and the CGM of which, the *Dexcom G6* CGM, is also covered by BC Pharmacare) with experimental proprietary software (approved by the FDA in 2022-May).
 
 * The *Ypsomed* tubed system (the pump of which, the *Ypsopump*, is covered by BC Pharmacare and the CGM of which, the *Dexcom G6* CGM, is also covered by BC Pharmacare) with experimental CAMAPS software (approved by the EMA in 2021).

## This Consent and Waiver

This consent and waiver covers the experimental use of three experimental software systems: *Loop, freeAPS X* and *androidAPS* (DIY smartphone apps, together Closed Loop Apps) that work in conjunction with approved devices like the *Dexcom G6* CGM and the tubeless *Omnipod* insulin pump. The Closed Loop Apps are not approved by Health Canada, the FDA or the EMA. However, *Loop* was [submitted](http://bit.ly/loop_safety_study) to the FDA for approval on June 12, 2020 by **Tidepool** (a 501(c)(3) nonprofit organization) based on [an observational study of 873 Loopers](http://bit.ly/loop_safety_study) as its primary evidence. 

In early 2021 [Lum and colleagues described self-reported outcomes for 553 Loopers](https://drive.google.com/file/d/1SkIitgUFu6Xg7TkjPxuDvRQm7HA4xoaU/view?usp=sharing). *AndroidAPS* was shown to be safe and efficacious in a study of 12 subjects by [Gawrecki and colleagues 2021-Apr-5](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0248965&type=printable) -- because *freeAPSX* uses the same AP algorithm as *androidAPS* (openAPS) -- it is assumed that *freeAPSX* is equally as safe and efficacious as *androidAPS*. As of 2022-Jul-26 **BCDiabetes** has installed and supported [171 *Type 1* clients with Loop (n=58), androidAPS (n=12) and freeAPSX (n=101)](https://bit.ly/3lbeWKC) for 3+ months with no episodes of severe hypoglycaemia or DKA and average improvements in Time in Range and A1c of 19% and 0.7% respectively accompanied by [significant reductions in Diabetes Distress and Fear of Hypoglycemia](https://bit.ly/3lbeWKC). However, the number of systems installed and supported and the related data remain limited. 

### Hardware Components

The hardware components of these three Closed Loop App systems (the *Omnipod* pump and *Dexcom G6*) are both covered by BC Pharmacare and approved by Health Canada.

* **BCDiabetes** has observed through its support of patients using the experimental Closed Loop App APSs that these Closed Looped App systems offer equivalent or superior glucose control/incidence of severe hypoglycaemia and quality of life when compared to [*Medtronic*](https://bit.ly/Medtronic670) and [*Tandem*](https://bit.ly/Tandem_C_IQ) systems approved by Health Canada and the [*Omnipod* 5*](https://bit.ly/*Omnipod*5) FDA-approved system at a lower price (hardware covered by BC Pharmacare). 

* For these reasons, **BCDiabetes** offers to support patients wishing to use Close Loop Apps with the *Omnipod* pump and *Riley link*. 

### Possible Risks

Possible risks relating to use of all APSs, including the *Closed Loop App APSs*, include the risk of infection, irritation and/or slight discomfort at the points of insertion for the *Dexcom G6* sensors and *Omnipod* patch pumps; certain side effects associated with participants' medical condition and their AID therapy; hypoglycaemia; and hyperglycaemia.

## Agreement

I hereby consent to treatment with a *Closed Loop App APS* and to receive services and advice from **BCDiabetes** with full knowledge and assumption of all associated risks. I hereby grant **BCDiabetes** (as well as its directors, officers, employees, insurers, agents, shareholders, affiliated corporations, predecessors, successors, beneficiaries and assigns) a full, final and complete release and discharge from any and all past, present or future complaint, demand, claims, causes of action, suits, rights, damages, losses, liabilities and costs of any nature and kind whatsoever (including for personal injury and death), howsoever arising, whether currently known or unknown, resulting from, arising out of or relating to, directly or indirectly, all services and advices rendered by **BCDiabetes**, including in connection with the use of any of the Closed Loop Apps.

By installing a Closed Loop App on my phone (or a phone provided to me by **BCDiabetes**) with the assistance of **BCDiabetes** employees, I, the undersigned, hereby:

i) Confirm that I had otherwise planned to set up a Closed Loop App myself using a standard DIY installation however given its complexity I consider that it is in my best interest to have the installation done professionally at **BCDiabetes**;

ii) Understand the nature and anticipated effect of what is proposed including the significant risks and Health Canada approved alternatives available have been explained to me and I am satisfied with these explanations and I have understood them;

iii) Understand that the *Dexcom G6* and the *Omnipod* insulin patch pump are both approved by the FDA and Health Canada for the treatment of *Type 1* and *Type 2* diabetes in patients 2 years old and older. 

iv) Wish to have a Closed Loop App configured and installed on my personal phone in order to treat my *Type 1* or *Type 2* diabetes and I confirm that I understand the risks of this experimental treatment technology and the off label use of the *Dexcom G6* and the *Omnipod* insulin pump and I am willing to accept the potential risks that my physician has described and discussed with me. 

v) Acknowledge that there may be other, unknown risks relating to the use of the Closed Loop Apps;

vi) Understand that the Closed Loop Apps, the software driving my *Omnipod* pump based on CGM readings from a *Dexcom G6* (or *Freestyle Libre* device) relayed in some cases via a radio transmitter device (*Orangelink* or other similar device), are part of experimental projects known as *Loop*, *freeAPSX* and *androidAPS* respectively and are not approved by Health Canada;

vii) Assume full responsibility for running the entire system (Looping with smartphone, *Omnipod*, *Dexcom G6*/*Freestyle Libre*, *Riley Link* and *Loop* app) and understand that I do so at my own risk;

viii) Understand that the iOS Closed Loop Apps are shared by **BCDiabetes** with their patients and clients through **BCDiabetes** Apple Developer *TestFlight* account where the Closed Loop Apps have a useful life of 90 days. To provide continuity of app support by **BCDiabetes**, software engineers renew the Closed Loop Apps developer license every 75-80 days, provided however that approval of Apple is obtained in order for a new app to be released. Apple has the right to refuse or delay approval of a release, which could interrupt renewal or access to the Closed Loop Apps at expiry through TestFlight. As such, I understand that **BCDiabetes** does not guarantee access to updated/renewed iOS Closed Loop Apps through their Apple Developer TestFlight account;

ix) Understand and accept that, at any time without notification, the Closed Loop Apps may no longer be available without prior notice; 

x) In the event Close Loop App access is interrupted or canceled, I understand that I will need to immediately revert to an alternative insulin delivery system (retail or otherwise) to manage my diabetes or build the app myself from source code;

xi) Agree not to copy (except for reasons of personal secure backup) or share this Closed Loop Apps with any other individual or entity without the express written consent of **BCDiabetes**.

### Individual Patient Data (IPD) Sharing Statement

The datasets generated during and/or analyzed during the patient use of any Closed Loop Apps supported by **BCDiabetes** will be stored in a secure non-publicly available cloud repository maintained by Google Canada. With the patients written consent, the data collected during the use of the Closed Loop Apps will also be added to your electronic medical record at **BCDiabetes**. All the datasets generated during and/or analyzed during the use of the Closed Loop Apps will remain confidential to the extent provided by law. Patients will only be identified by a code number. The key to the code linking participants to their data will be kept by the **BCDiabetes**. **BCDiabetes** could forward your coded data to the DIYAID community for the purpose of improving algorithms. **BCDiabetes** could also forward your coded data to healthcare authorities (e.g., Health Canada) for the purpose of assessing the benefits and limitations of different AID systems. However, **BCDiabetes** and any entities who receive the research data will respect the confidentiality rules in effect in British Columbia and Canada regardless of the country to which your data may be transferred. The data will be stored for at least 7 years beyond your last appointment with **BCDiabetes** as required by the laws of British Columbia.

### Governing Law

The Parties acknowledge and agree that the execution of this Informed Consent has not been induced by, nor do the Parties rely upon, any representations that are not expressly incorporated into this Informed Consent.

The Parties hereby agree that their relationship and the resolution of any and all disputes arising therefrom, including any issues related to this Informed Consent, shall be governed by and construed in accordance with the laws of the province of British Columbia and the laws of Canada applicable therein.

### Jurisdiction

The Parties hereby acknowledge that the services will be provided in the province of British Columbia and that the Courts of the province of British Columbia shall have sole and exclusive jurisdiction to entertain any complaint, demand, claim, cause of action or suit whatsoever arising out of all services and advices rendered by **BCDiabetes**, including in connection with the use of any of the Closed Loop Apps, as well as of this Informed Consent. The parties hereby agree that if either of them commences any such legal proceedings they will only be commenced in the province of British Columbia and hereby irrevocably submit to the exclusive jurisdiction of the Courts of the province of British Columbia.

### Consent

I have read the foregoing information, or it has been read to me. I have had the opportunity to ask questions about it and any questions that I have asked have been answered to my satisfaction. I consent voluntarily to use the Closed Loop Apps.

Dated: July 30, 2022
