# Dynamic ISF

The idea behind *dynISF* is that ISF isn't a fixed number but changes as BG changes, e.g. if your BG climbs higher, your **Insulin Sensitivity** drops and you need more insulin.

## Adjustment Factor
*Settings --> Preferences --> Dynamic Settings --> Adjustment Factor*

**Adjustment Factor is a multiplier that impacts insulin delivery**. It’s just a way of turning up or down the aggressiveness/slope of ISF curve. It determines the aggressiveness of the *DynamicISF* algorithm, and it tends to be person-specific.

### Switch On *Sigmoid Function*

*Settings -> Preferences -> Dynamic Settings -> Use Sigmoid Function*

The **Sigmoid Function** uses a *Logarithmic Scale* to calculate *Dynamic ISF*. If you are just switching to using it, you can get to a ballpark *Adjustment Factor* with the *Sigmoid Function* enabled by dividing what you have now by 1.666. 

**NOTE: This is only your new starting point. You will need to make further adjustments to suit your condition.**

The actual formula is:

```
F = 1800 / profile.sens * tdd_averages.average_14days * LN( profile.min_bg / ( 120 - pumpprofile.insulinPeakTime + 1 )
```

Each of the above variables points to the Debug Options screen + variable within it that you would need to use, but again, this will get you only to ballpark: you will want to monitor and tweak *Adjustment Factor* accordingly. 

If you find it's not aggressive enough, increase AF, if it's too aggressive, decrease AF.

NOTE: You can use a different value for *tdd_averages.average_14days* if you want. This smooths out the good and bad days that we all have.

### Ballpark Formula

There is a formula for deriving an approximate number to begin with:

```
adjustmentFactor = 277700/TDD * BG_target * (18 * 18) * StaticISF
```

* **Total Daily Delivery (TDD)** can be found by tapping the green circle at the top of the main iAPS page. There are three numbers in the purple area: TDD, Weighted Average (Wavg), and 14day. Use the TDD value. 

* *BG_Target* is whatever you have chosen for your target, e.g. 5.5.

* **Use the *Autotune* value for *StaticISF***
  * *Settings --> Configuration --> Autotune*

Autotune runs automatically every day, but you may want to run it now if it hasn't run for a while.

* The Autotune value also can be found in 
  * *Settings -> Configuration --> Insulin Sensitivities --> Autotune --> Calculated Sensitivity*

Using some example numbers, the *AdjustmentFactor* will be:

```
277700 / ( 2.31 * 78.75 * 5.5 * ( 18 * 18 ) * 2.31) = 0.856
```

It isn't 100% accurate, but it gets you into the ballpark range, and you can tweak up or down from there.

## AutoSens

**Basically, *AutoSens* determines how sensitive or resistant you are to insulin**. Its value is dynamically calculated by the system.

**If *Autosens* is calculated to be `1`**, it means that there is no change from those *Settings* that affect insulin delivery.

* **More than `1`** means that you need **more insulin** than usual
* **Less than `1`** means you are currently **more sensitive** and need less insulin

### Autosens Default Settings

**The default *Autosens* settings** are *Autosens Max: 1.2* and *Autosens Min: 0.8*. The only way to always have *Autosens* set to `1` (disabling both *Autosens* and *Dynamic ISF*) is to have both *Autosens Max* and *Autosens Min* set to `1`.

***Oref0* can of course compute your *Autosens* to `1`** (when not using *Dynamic ISF*). This happens on two occasions:

1. When there isn’t enough data for *Autosens*, and
2. When the *Autosens functions* don’t compute a change in insulin sensitivity.

### Autosens Can Be Disabled

***Autosens* is disabled (actually overridden)** when using *Dynamic ISF*, except for the exception when you’re using a high *Temp target* together with one of the two exercise settings, because at these occasions *Dynamic ISF* gets temporarily disabled.

***Dynamic ISF* borrows the *Autosens Max.Min* settings** for limiting the dynamic ratio. So even it it’s still called *Autosen Max/Min*, it isn’t an *Autosens setting* when you have *Dynamic ISF* toggled on.

A full explanation of *AutoSens* can found in the [OpenAPS documentation](https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/autosens.html).

