# Display Commands

## Sidebar

### Show/Hide
The first button on the toolbar can toggle the visibility of the sidebar. You can also hit the `S` key on your keyboard to do the same thing. If you close the sidebar, it will remain closed the next time you open the book.

### Search
The second button on the toolbar is the search button, keyboard shortcut `F` (Find). 
* Click the button to see a *Search Box*. As you type in the box, you will see only sections that match the search keyword. 
* Use the `Arrow Keys [Up/Down]` to highlight the previous/next match in the search results. 
* Click the `Search Button` again (or hit F outside the `Search Box`). The search keyword will be emptied and the search box will be hidden.

### Theme settings
The third button is for Font/Theme settings. You can:
* Change the `font size` (bigger/smaller), the `font family` (serif/sans serif), and the `theme` (White, Sepia, or Night). 

### Downloads
The `Download Button` lets you download files.
* All downloadable file types are displayed in a drop-down menu, and the filename extensions are used as the menu text.

### Sharing
On the right of the toolbar are buttons to share the link on social network websites such as Twitter, Facebook, and Linkedin.

### Information
The Information (‘i’) Button lists keyboard shortcuts available to navigate the document. 
