## Recommended Insulin Fraction (RIF)

*Settings —> Preferences —> FREEAPS X —>Recommended Insulin Fraction*

**Your RIF should be at 2, which is the default**. The only reason you should ever lower it is if TWO things are happening:
   1. Your blood sugar (b/s) is going low, AND
   2. After giving a manual bolus, SMBs are NOT happening

**If SMBs are still being enacted after changing your RIF, it is now TOO LOW**. These extra SMBs will now be pushing your b/s down and you will experience lows.

**If BOTH the above conditions are NOT happening**, all you will be achieving by lowering your RIF is to prolong your highs.